# docker-compose.yml
version: '3.8'

networks:
  nginx-proxy-network:
    external: true

volumes:
  pg:
  conf:
  vhost:
  html:
  certs:
  acme:
  db_backup:

services:
  meme_archives_db:
    image: "postgres:16.1"
    container_name: "meme_archives_db"
    env_file:
      - "../config/meme-archives-db.env"
    volumes:
      - "pg:/var/lib/postgresql/data"
      - "db_backup:/mnt"
    restart: "always"
    networks:
      - nginx-proxy-network

  # meme_archives_db is not exposed to the outside world,
  # so it does not depends_on nginx_proxy

  nginx_proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../nginx/nginx.conf:/etc/nginx/conf.d/custom-config.conf:ro
    networks:
      - nginx-proxy-network

  acme_companion:
    image: nginxproxy/acme-companion
    container_name: acme_companion
    env_file:
      - "../config/acme-companion.env"
    volumes_from:
      - nginx_proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nginx-proxy-network

  meme_archives_api:
    build: "../../meme-archives-api/"
    image: meme-archives-api
    container_name: "meme_archives_api"
    env_file:
      - "../../meme-archives-api/.env"
    restart: "always"
    depends_on:
      - nginx_proxy
      - meme_archives_db
    networks:
      - nginx-proxy-network
    environment:
      - VIRTUAL_HOST=
      - VIRTUAL_PORT=4321
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
    command: npm start
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  meme_archives_tg_bot:
    build: "../../meme-archives-tg-bot/"
    image: meme-archives-tg-bot
    container_name: "meme_archives_tg_bot"
    env_file:
      - "../../meme-archives-tg-bot/.env"
    restart: "always"
    depends_on:
      - nginx_proxy
    networks:
      - nginx-proxy-network
    environment:
      - VIRTUAL_HOST=
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
    command: npm start
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  meme_archives_web:
    build: "../../meme-archives-web/"
    image: meme-archives-web
    container_name: "meme_archives_web"
    # Next.js runtime environment variables need to be available
    # before the build command runs in the Dockerfile, so the
    # env_file does not even need to be specified here, because
    # npm run build will automatically grab the ./.env.local file
    # that is in the meme-archives-web directory.
    # env_file:
    #   - "../config/meme-archives-web.env"
    restart: "always"
    environment:
      - VIRTUAL_HOST=
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
    depends_on:
      - meme_archives_api
    networks:
      - nginx-proxy-network
    command: npm start
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"
